MusicApp/config/routes.rb
Rails.application.routes.draw do
  # get 'users/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create, :show]
  resources :bands

  resource :session, only: [:new, :create, :destroy]
end

MusicApp/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  year       :integer          not null
#  live       :boolean          default(FALSE), not null
#  band_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ApplicationRecord
    validates :title, :year, :live, :band_id, presence: true
    validates :band_id, uniqueness: { scope: :title, message: "should only have one album by a given name." }
    after_intialize :set_defaults

    def set_defaults
        self.live ||= FALSE
    end

    belongs_to :band,
        foreign_key: :band_id,
        class_name: 'Band'
end

MusicApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

MusicApp/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
    validates :name, presence: true, uniqueness: true

    has_many :albums,
        foreign_key: :band_id,
        class_name: 'Album'
end

MusicApp/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
    validates :email, :password_digest, :session_token, presence: true
    validates :email, :session_token, uniqueness: true
    validates :password, length: { minimum: 6 }, allow_nil: true
    after_initialize :ensure_session_token
    
    attr_reader :password

    def self.generate_session_token 
        SecureRandom::urlsafe_base64
    end

    def ensure_session_token
        self.session_token ||= User.generate_session_token
    end

    def reset_session_token!
        self.session_token = User.generate_session_token
        self.save!
        self.session_token
    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def self.find_by_credentials(email, password)
        user = User.find_by(email: email)
        return nil unless user
        user.is_password?(password) ? user : nil
    end
end

MusicApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def logged_in?
        !!current_user
    end

    def login!(user)
        session[:session_token] = user.reset_session_token!
    end

    def logout_user!
        current_user.reset_session_token! if logged_in?
        session[:session_token] = nil
        @current_user = nil
    end
end

MusicApp/app/controllers/bands_controller.rb
class BandsController < ApplicationController
    def index
        # @band = Band.find_by(id: params[:id])
        @bands = Band.all
        render :index
    end

    def show
        @band = Band.find_by(id: params[:id])
        # redirect_to band_url(@band)
        render :show
    end

    def new
    end

    def create
        @band = Band.new(band_params)

        if @band.save
            redirect_to band_url(@band)
        else
            render json: Band.errors.full_messages
        end
    end

    def edit
        @band = Band.find_by(id: params[:id])
        render :edit
    end

    def update
        @band = Band.find_by(id: params[:id])
        
        if @band.update_attributes(band_params)
            redirect_to band_url(@band)
        else
            render json: 'error'
        end
    end

    def destroy
        @band = Band.find_by(id: params[:id])
        
        if @band.destroy
            redirect_to bands_url
        else
            render json: 'destroy failed'
        end
    end

    private

    def band_params
        params.require(:bands).permit(:name)
    end
end

MusicApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        @user = User.find_by_credentials(params[:users][:email], params[:users][:password])

        if @user
            login!(@user)
            redirect_to bands_url
        else
            flash.now[:errors] = ['Invalid credentials.']
            render :new
        end
    end

    def destroy
        logout_user!
        redirect_to new_session_url
    end
end

MusicApp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      redirect_to bands_url
    else
      render json: @user.errors.full_messages
    end
  end

  def show
    @user = User.find_by(id: params[:id])

    render :show
  end

  private

  def user_params
    params.require(:users).permit(:email, :password)
  end
end

MusicApp/app/helpers/application_helper.rb
module ApplicationHelper
end

MusicApp/app/helpers/bands_helper.rb
module BandsHelper
end

MusicApp/app/helpers/sessions_helper.rb
module SessionsHelper
end

MusicApp/app/helpers/users_helper.rb
module UsersHelper
end

MusicApp/app/views/bands/edit.html.erb
<h2>Edit Band</h2>

<form action="<%= band_url(@band) %>" method="POST">
<input type="hidden" name="_method" value="PATCH">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <label>Name
        <input type="text" name="bands[name]" value="">
    </label>
    <br>
    <br>
    <input type="submit" value="Submit">
</form>

MusicApp/app/views/bands/index.html.erb
<h2>Bands</h2>

<% @bands.each do |band| %>
    <a href="<%= band_url(band) %>"><%= band.name %></a>
    <br>
    <br>
<% end %>
<br>
<br>
<a href="<%= new_band_url %>">Create a Band</a>

MusicApp/app/views/bands/new.html.erb
<h2>New Band</h2>

<form action="<%= bands_url %>" method="POST">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <label>Band
        <input type="text" name="bands[name]" value="">
    </label>
    <br>
    <br>
    <input type="submit" value="Submit">
</form>

MusicApp/app/views/bands/show.html.erb
<h2> <%= @band.name %> </h2>

<a href="<%= bands_url %>">All Bands</a>
<a href="<%= edit_band_url %>">Edit Band</a>
<br>
<form action="<%= band_url(@band) %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="DELETE">
    <input type="submit" value="Destroy Band">
</form>

MusicApp/app/views/layouts/application.html.erb
<style>
header, header ul {
  display: flex;
  align-items: center;
  justify-content: space-between;
  background-color: #111;
  color: steelblue;
  font-family: impact;
  border-radius: 20px;
  padding: 5px 20px;
}

header {
  font-size: 150%;
}

body {
  /* display: flex; */
  /* background-color: blue;
  justify-content: space-between;
  align-items: center; */
  /* background-color: #111; */
  /* color: steelblue; */
  /* font-family: impact; */
  /* font-size: 150%; */
  /* border-radius: 20px; */
  /* padding: 5px 20px; */
}

header ul li {
  list-style: none;
}

.button {
  border: none;
  border-radius: 10px;
  background-color: #111;
  color: steelblue;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
}

h2 {
  color: steelblue;
  font-family: impact;
  font-size: 200%;
}

p {
  color: steelblue;
  font-family: Arial, Helvetica, sans-serif;
  font-size: 100%;
}

body {
  background-color: silver;
}

#current-user {
  display: flex;
  background-color: #111;
  display: flex;
  flex-direction: row;
  background-color: #4CAF50; /* Green */
  border: none;
  color: white;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
}

input[type=submit] {
  display: flex;
  align-items: center;
  justify-content: space-between;
  font-family: impact;
  font-size: 100%;
  color: steelblue;
  background: #111;
  border: none;
  padding: 15px 32px;
  border-radius: 10px;
}

</style>

<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <h1>MusicApp</h1>
      <% if logged_in? %>
        <ul>
          <form action="<%= session_url %>" method="POST">
            <input class="button" type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <input class="button" type="hidden" name="_method" value="DELETE">
          <li><input class="button" type="submit" value="Sign Out"></li> 
        </ul>
      <% else %>
        <ul>
          <li><a class="button" href="<%= new_session_url %>"> Log In </a></li>
          <li><a class="button" href="<%= new_user_url %>"> Sign Up </a></li>
        </ul>
      <% end %>
  </header>

  <body>
    <% if flash[:errors] %>
        <% flash[:errors].each do |error| %>
        <p style="color: red"> <%= error %> </p>
      <% end %>
    <% end %>

    <div class="user-status">
      <% if logged_in? %>
        <p id="current-user">Logged in as: <%= current_user.email %></p>
        </form>
      <% end %>
    </div>



    <%= yield %>
  </body>
</html>

MusicApp/app/views/users/new.html.erb
<h2>Create an Account</h2>

<form action="<%= users_url %>" method="POST">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <label>Email
        <input type="text" name="users[email]" value="">
    </label>
    <br>
    <br>
    <label>Password
        <input type="password" name="users[password]" value="">
    </label>
    <br>
    <br>
    <input type="submit" value="Submit">
</form>

MusicApp/app/views/users/show.html.erb
<h2>User Profile</h2>
<p>Welcome, <%= @user.email %>!</p>